apiVersion: v1
  kind: Service
  metadata:
    labels:
    name: kubernetes 
  spec:
    selector:
      app: flatris
    ports:
       port: 443
     - protocol: TCP
       targetPort: 443
    sessionAffinity: None
    type: loadBalancer

apiVersion: apps/v1
    kind: Deployment
metadata:
  name: skillbox
  labels:
    app: flatris
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flatris
  minReadySeconds: 10
   template:
    metadata:
      labels:
        app: flatris
    spec:
      containers:
      - name: skillbox
        image: registry.gitlab.com/ivkosarev1/skillbox1:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000